apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    type: database
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:8.0.10
      command:
        - /bin/bash
        - -c
      env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "Ezio3946"
      ports:
        - containerPort: 27017
