apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
  labels:
    app: microservice-seguridad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-seguridad
  template:
    metadata:
      labels:
        app: microservice-seguridad
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env: 
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Ezio3946"  # Change this to a strong password